# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.runs/synth_1/Top_module.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param synth.incrementalSynthesisCache {C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/.Xil/Vivado-2312-asdf/incrSyn}
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.cache/wt} [current_project]
set_property parent.project_path {C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo {c:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  {C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.srcs/sources_1/FND_CNTL/BCD.v}
  {C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.srcs/sources_1/FND_CNTL/CLK_Divider.v}
  {C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.srcs/sources_1/FND_CNTL/Counter.v}
  {C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.srcs/sources_1/FND_CNTL/Decoder2to4.v}
  {C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.srcs/sources_1/FND_CNTL/Digit_splitter.v}
  {C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.srcs/sources_1/FND_CNTL/MUX.v}
  {C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.srcs/sources_1/uart/Rx.v}
  {C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.srcs/sources_1/control unit/watch_stopwatch_cntl/STOPWATCH_control_unit.v}
  {C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.srcs/sources_1/Data_path_unit/Smart_Button_Controller.v}
  {C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.srcs/sources_1/Data_path_unit/StopWatch_Data_path.v}
  {C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.srcs/sources_1/FND_CNTL/TOP_FND_CNTL.v}
  {C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.srcs/sources_1/Input_unit/TOP_btn.v}
  {C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.srcs/sources_1/control unit/watch_stopwatch_cntl/TOP_control_unit.v}
  {C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.srcs/sources_1/Data_path_unit/TOP_data_path.v}
  {C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.srcs/sources_1/Data_path_unit/Tick_generator.v}
  {C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.srcs/sources_1/FIFO/Top_FIFO.v}
  {C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.srcs/sources_1/uart/Tx.v}
  {C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.srcs/sources_1/uart/UART_TOP_module.v}
  {C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.srcs/sources_1/control unit/watch_stopwatch_cntl/WATCH_control_unit.v}
  {C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.srcs/sources_1/Data_path_unit/Watch_Data_path.v}
  {C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.srcs/sources_1/ascii/ascii_sender.v}
  {C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.srcs/sources_1/ascii/ascill_decoder.v}
  {C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.srcs/sources_1/uart/baud_tick_16oversample.v}
  {C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.srcs/sources_1/Input_unit/btn_debounce.v}
  {C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.srcs/sources_1/control unit/control_top.v}
  {C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.srcs/sources_1/control unit/dht11_controller.v}
  {C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.srcs/sources_1/FND_CNTL/dot_onoff.v}
  {C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.srcs/sources_1/FIFO/fifo_control.v}
  {C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.srcs/sources_1/FIFO/fifo_fsm.v}
  {C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.srcs/sources_1/FIFO/fifo_register.v}
  {C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.srcs/sources_1/sensor_timer.v}
  {C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.srcs/sources_1/control unit/sr04_controller.v}
  {C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.srcs/sources_1/control unit/tick_gen_1us.v}
  {C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.srcs/sources_1/Data_path_unit/tick_time_counter.v}
  {C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.srcs/sources_1/Top_module.v}
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.srcs/constrs_1/imports/Ondevice_verilog/Basys-3-Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/nayun/verilog20.2/Ondevice_verilog/sensor_project/Integrated Project/Integrated Project.srcs/constrs_1/imports/Ondevice_verilog/Basys-3-Master.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top Top_module -part xc7a35tcpg236-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_module.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_module_utilization_synth.rpt -pb Top_module_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
